spring:
  datasource:
    name: blog
    generate-unique-name: false
  h2:
    console:
      enabled: true
# http://localhost:8090/h2-console/
# url=jdbc:h2:mem:blog user=SA
# SELECT * FROM ENTITY_EXAMPLE
server:
  port: 8090
